<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $connection = 'mysql2'; // Koneksi ke database sumber (serverbc)
    protected $table = 'barang';
    protected $primaryKey = 'kode';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'kode',
        'nama',
        'kategori',
        'golongan',
        'subgolongan1',
        'subgolongan2',
        'satuanbeli',
        'satuan',
        'satuan2',
        'satuan3',
        'isi',
        'isi2',
        'isi3',
        'elektrik',
        'sn',
        'master',
        'tr_saldo',
        'nol_price',
        'nol_price_diskon',
        'toko',
        'gudang',
        'hpp',
        'harga_toko',
        'harga_toko2',
        'harga_toko3',
        'harga_partai',
        'harga_partai2',
        'harga_partai3',
        'harga_cabang',
        'harga_cabang2',
        'harga_cabang3',
        'diskon',
        'point',
        'point_m',
        'jenis',
        'sinkron',
        'stokmin',
        'stokmax',
        'warningstok',
        'jenis_point',
        'point_k1',
        'point_k2',
        'gambar',
        'harga_karyawan',
        'harga_member',
        'ukuran',
        'supplier',
        'pajak',
        'kode_barcode',
        'kode_barcode2',
        'kode_barcode3',
        'diskon2',
        'gambar2',
        'margin_toko',
        'margin_toko2',
        'margin_toko3',
        'margin_partai',
        'margin_partai2',
        'margin_partai3',
        'margin_cabang',
        'margin_cabang2',
        'margin_cabang3',
        'tgl_terakhir',
        'tampil',
        'diskon_beli',
        'warna',
        'sudah_ppn',
        'nilaippn',
        'expired',
        'ket',
        'ada_expired_date',
        'paket',
        'diskon_toko',
        'diskon_partai',
        'diskon_cabang',
        'komisi_spg',
        'lokasi',
        'merk',
        'cek',
        'tipe_disc_member',
        'jum_diskon_member',
        'jum_komisi_sales',
        'harga_terakhir',
        'keterangan_foto',
        'nama2',
        'nama3',
        'toko_rusak',
        'gudang_rusak',
        'stokmin_gudang',
        'stokmax_gudang',
    ];

    protected $casts = [
        'isi' => 'decimal:2',
        'isi2' => 'decimal:2',
        'isi3' => 'decimal:2',
        'toko' => 'decimal:2',
        'gudang' => 'decimal:2',
        'hpp' => 'decimal:2',
        'harga_toko' => 'decimal:2',
        'harga_toko2' => 'decimal:2',
        'harga_toko3' => 'decimal:2',
        'harga_partai' => 'decimal:2',
        'harga_partai2' => 'decimal:2',
        'harga_partai3' => 'decimal:2',
        'harga_cabang' => 'decimal:2',
        'harga_cabang2' => 'decimal:2',
        'harga_cabang3' => 'decimal:2',
        'diskon' => 'decimal:2',
        'point' => 'decimal:2',
        'point_m' => 'decimal:2',
        'stokmin' => 'decimal:2',
        'stokmax' => 'decimal:2',
        'warningstok' => 'decimal:2',
        'point_k1' => 'decimal:2',
        'point_k2' => 'decimal:2',
        'harga_karyawan' => 'decimal:2',
        'harga_member' => 'decimal:2',
        'diskon2' => 'decimal:2',
        'margin_toko' => 'decimal:2',
        'margin_toko2' => 'decimal:2',
        'margin_toko3' => 'decimal:2',
        'margin_partai' => 'decimal:2',
        'margin_partai2' => 'decimal:2',
        'margin_partai3' => 'decimal:2',
        'margin_cabang' => 'decimal:2',
        'margin_cabang2' => 'decimal:2',
        'margin_cabang3' => 'decimal:2',
        'nilaippn' => 'decimal:2',
        'jum_diskon_member' => 'decimal:2',
        'jum_komisi_sales' => 'decimal:2',
        'harga_terakhir' => 'decimal:2',
        'toko_rusak' => 'decimal:2',
        'gudang_rusak' => 'decimal:2',
        'stokmin_gudang' => 'decimal:2',
        'stokmax_gudang' => 'decimal:2',
        'elektrik' => 'boolean',
        'sn' => 'boolean',
        'tr_saldo' => 'boolean',
        'nol_price' => 'boolean',
        'nol_price_diskon' => 'boolean',
        'sinkron' => 'boolean',
        'sudah_ppn' => 'boolean',
        'ada_expired_date' => 'boolean',
        'paket' => 'boolean',
        'komisi_spg' => 'boolean',
        'cek' => 'boolean',
        'tampil' => 'boolean',
    ];
}
